### ISSUE TITLE
Stupid question, how do you install this plugin?!

### ISSUE THREAD

**Issue by imougy** [ichitaro/xd-copy-html-css#2]
Placing it under adobe XD/develop and running yarn install doesn't do the trick.
Do I have to manually put main.js under the plugin folder? I don't think so.
Thanks for the help.

**Comment by ichitaro** [comment]
Download the latest `.xdx` file from [the releases page](https://github.com/ichitaro/xd-copy-html-css/releases) and double-click to install it.

**Comment by imougy** [comment]
Awesome!
Thank you so much, fantastic work.
